spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_online
    username: postgres
    password: hiusahald
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: hiusahald@gmail.com
    password: spbi igbe sduc goue
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  servlet:
    context-path: /api/v1
  port: 270704

app:
  mailing:
    from: hiusahald@gmail.com
  security:
    jwt:
      expiration: 86400000
      secret-key: dsfdthst435465uytr3r254thrgrsefw345fgds587993dg