spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_app_test_v1
    username: postgres
    password: hiusahald
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: hiusahald@gmail.com
    password: spbi igbe sduc goue
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  servlet:
    context-path: /api/v1
  port: 9000

app:
  storage:
    cloudinary:
      cloud-name: dvlnioxyc
      api-key: 599956947274682
      api-secret: Dtgb65pFAagi47mnc_Llbb7MafQ
      cloud-url: cloudinary://599956947274682:Dtgb65pFAagi47mnc_Llbb7MafQ@dvlnioxyc
      connection-timeout: 5000
      buffer-length: 1024
  mailing:
    from: hiusahald@gmail.com
    activate-account:
      redirect-url: localhost:3000/activate-account
      token-length: 6
      token-expiration: 900000
  security:
    jwt:
      expiration: 86400000
      secret-key: dsfdthst435465uytr3r254thrgrsefw345fgds587993dg
  frontend:
    origin: http://localhost:3000
  backend:
    origin: http://localhost:9000