spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db_aaa
    username: postgres
    password: hiusahald
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: hiusahald@gmail.com
    password: spbi igbe sduc goue
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  servlet:
    context-path: /api/v1
  port: 8081

app:
  storage:
    cloudinary:
      cloud-name: dvlnioxyc
      api-key: 599956947274682
      api-secret: Dtgb65pFAagi47mnc_Llbb7MafQ
      cloud-url: cloudinary://599956947274682:Dtgb65pFAagi47mnc_Llbb7MafQ@dvlnioxyc
      connection-timeout: 5000
      buffer-length: 1024
  mailing:
    from: hiusahald@gmail.com
    url:
      activate-account: localhost:3000/activate-account
  security:
    jwt:
      expiration: 86400000
      secret-key: dsfdthst435465uytr3r254thrgrsefw345fgds587993dg